services:
  - type: web
    name: virtual-office-api
    env: node
    rootDir: backened
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
  - type: web
    name: virtual-office-realtime
    env: node
    rootDir: realtime-backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
